### ISSUE TITLE
build error/problems

### ISSUE THREAD

**Issue by tribual** [Moyster/o_vendor_mediatek#12]
Hi!

Trying to build for Elephone P9000. But getting build error. 
https://hastebin.com/muzibekahi.makefile

Also seen that path to patches not correct:
In readme: 
. vendor/mediatek/install.sh & . vendor/mediatek/uninstall.sh
Should be:
. vendor/mediatek/patches/install.sh & . vendor/mediatek/patches/uninstall.sh

And some patches not apply correctly. Send you a Hangouts. Hope for answer...

**Comment by ChalapathiRevanth** [comment]
First Of all  did u check the branch? this branch is los15, and these patches work in only 8.0 Roms!! These patches cant compile 8.1.0 Roms!! @Moyster u need to update ur patches in your free time. 

@tribual  I hope u got your answer

**Comment by tribual** [comment]
You're right. My fault. Used accidentally 8.1 sources. Now with 8.0 patches installed fine and build seems to start correctly. 

Many thanks for the hint!

**Comment by ChalapathiRevanth** [comment]
@tribual  U can close this Issue Now!
